#!/usr/bin/env bash

# Update packages and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Define the custom header value
header_value=$(hostname)

# Add the custom header to Nginx configuration
sudo sed -i "/server_name _;/a \        add_header X-Served-By \"$header_value\";" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
